#!/usr/bin/env python
"""
Copyright 2014 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Names:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'c': 'str',
            'clisp': 'str',
            'clojure': 'str',
            'cpp': 'str',
            'csharp': 'str',
            'erlang': 'str',
            'go': 'str',
            'haskell': 'str',
            'java': 'str',
            'lua': 'str',
            'perl': 'str',
            'php': 'str',
            'python': 'str',
            'ruby': 'str',
            'scala': 'str'

        }


        #C
        self.c = None # str
        #Clisp
        self.clisp = None # str
        #Clojure
        self.clojure = None # str
        #Cpp
        self.cpp = None # str
        #Csharp
        self.csharp = None # str
        #Erlang
        self.erlang = None # str
        #Go
        self.go = None # str
        #Haskell
        self.haskell = None # str
        #Java
        self.java = None # str
        #Lua
        self.lua = None # str
        #Perl
        self.perl = None # str
        #Php
        self.php = None # str
        #Python
        self.python = None # str
        #Ruby
        self.ruby = None # str
        #Scala
        self.scala = None # str
        
